add error message

diff --git a/tests/Alltest b/tests/Alltest
--- a/tests/Alltest
+++ b/tests/Alltest
@@ -1,5 +1,4 @@
 #!/usr/bin/env sh
-set -e
 
 cd ${0%/*} || exit 1    # run from this directory
 
@@ -10,5 +9,12 @@ sed -e 's!endTime         900;!endTime         100;!g' system/controlDictOld > s
 rm system/controlDictOld
 ./Allrun
 
-cmp -s ../cavityResult.txt postProcessing/surfaces/100/gamma_L_interface.raw
+if ! cmp -s ../cavityResult.txt postProcessing/surfaces/100/gamma_L_interface.raw > /dev/null 2>&1
+then
+	echo "Failed: Different results for cavity example" 
+    exit 1
+else
+	echo "Passed: Same results for cavity example"
+fi 
+
 cd ..
